wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.show, name="show"),
    path("np/", views.new_page, name="new_page"),
    path("ep/", views.edit_page, name="edit_page"),
    path("random/", views.random_page, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from http.client import HTTPResponse
import random
import re
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
import markdown

from . import util

entries_list = util.list_entries()

def index(request):
    if request.method == "POST":
        query = request.POST.get("q")
        for i in entries_list:
            if query == i:
                return render(request, "encyclopedia/show.html", {
                    "entry": markdown.markdown(util.get_entry(query)),
                    "title": query
                })           
        
        #find a match
        low = util.lowering(entries_list)
        matches = list(filter(lambda x: query.lower() in x, low))
        
        #get original names
        print(entries_list)
        c_matches = list()
        for item in matches:
            for original in entries_list:
                if item == original.lower():
                    item = original
                    c_matches.append(item)
        #render them
        return render(request, "encyclopedia/index.html", {
            "entries": c_matches,
            "header": "Search Results"
        })
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "header": "All Pages"
        })

def show(request, title):
    for i in entries_list:
            if title.lower() == i.lower(): # I have to make it case insensitive because chrome keeps changing the URL
                title = i
                return render(request, "encyclopedia/show.html", {
                    "entry": markdown.markdown(util.get_entry(title)),
                    "title": title
                })
    if util.get_entry(title) is None:
        return render(request, "encyclopedia/error.html", {
            "message": "Requested page was not found"
        })

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="", widget=forms.Textarea())


def new_page(request):
    if request.method == "GET":
        return render(request, "encyclopedia/new_page.html", {
                "form": NewPageForm()
            })
    else:
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title) is None:
                util.save_entry(title, content)
                entries_list.append(title)
                return render(request, "encyclopedia/show.html", {
                    "entry": markdown.markdown(util.get_entry(title)),
                    "title": title
                })
            else:
                return render(request, "encyclopedia/error.html", {
                    "message": "This entry already exists"
                })

def edit_page(request):
    if request.method == "GET":
        form = NewPageForm()
        title = request.GET["title"]
        form.fields["title"].initial = title
        form.fields["title"].widget = forms.HiddenInput()
        form.fields["content"].initial = util.get_entry(title)
        return render(request, "encyclopedia/edit_page.html", {
            "form": form
            })
    else:
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return render(request, "encyclopedia/show.html", {
                "entry": markdown.markdown(util.get_entry(title)),
                "title": title
            })

def random_page(request):
    title = random.choice(entries_list)
    return render(request, "encyclopedia/show.html", {
                    "entry": markdown.markdown(util.get_entry(title)),
                    "title": title
                }) 

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <form action="{% url 'wiki:edit_page' %}" method="post">
        <input type="submit" value="Save">
        <hr>
        {% csrf_token %}
        {{ form }}
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>ERROR:</h1>
    <h3>{{ message }}</h3>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ header }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:show' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" autocomplete="off">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'wiki:new_page' %}" method="post">
        <input type="submit" value="Save">
        {% csrf_token %}
        {{ form }}
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/show.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    
    <p>{{ entry | safe }}</p>

    <hr>

    <form action="{% url 'wiki:edit_page' %}" method="get">
        <input type="hidden" value="{{ title }}" name="title">
        <input type="submit" value="Edit Entry">
    </form>

{% endblock %}